### ISSUE TITLE
Not spraying water, and when restarting resource it completely breaks the fire extinguisher

### ISSUE THREAD

**Issue by redcatjack** [symeRobinson/wetStinguisher#1]
Put resource in server, started via server.cfg, load in and it sprays the fire extinguisher normally (No water, just base game).
Tried restarting the script (/restart kd_hose) and now the fire fire extinguisher spays nothing. No errors via console.
https://i.imgur.com/n17srai.png

**Comment by symeRobinson** [comment]
Alright thanks for the feedback, I'll continue to work on it. This should be fixed once I get my computer up and running around sunday / monday. I appreciate the feedback!

**Comment by redcatjack** [comment]
Guessing this wont ever get fixed
